# Generated by Django 4.1.5 on 2023-02-01 02:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings_Account',
            fields=[
                ('savings_rubbish', models.CharField(max_length=30)),
                ('account_number', models.PositiveBigIntegerField(default=0, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Account',
            fields=[
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('nationality', django_countries.fields.CountryField(default='Nigeria', max_length=2)),
                ('account_type', models.CharField(choices=[('Current_Account', 'Current Account'), ('Savings_Account', 'Savings Account')], max_length=255)),
                ('account_number', models.PositiveBigIntegerField(default=0, primary_key=True, serialize=False)),
                ('funds', models.PositiveBigIntegerField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
