# Generated by Django 4.1.5 on 2023-01-30 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_savings_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings_account',
            name='account_number',
            field=models.PositiveBigIntegerField(default=datetime.datetime(2023, 1, 30, 17, 18, 32, 803217), primary_key=True, serialize=False),
        ),
    ]
