# Generated by Django 4.1.5 on 2023-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_createsavingsaccount_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcurrentaccount',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=20),
        ),
    ]
