# Generated by Django 4.1 on 2023-01-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_savings_account_savings_rubbish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_account',
            name='id',
        ),
        migrations.AddField(
            model_name='current_account',
            name='account_number',
            field=models.PositiveBigIntegerField(default=737458334978, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='current_account',
            name='current_rubbish',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='savings_account',
            name='account_number',
            field=models.PositiveBigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
