# Generated by Django 4.1.5 on 2023-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_extendeduser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
