# Generated by Django 4.1.7 on 2023-03-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_extendeduser_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
